/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tFnUhx0h36y
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "./ui/input";
import Image from "next/image"; // Import Image component from Next.js for optimized image handling

export function Navbar() {
  return (
    <div>
      <ul className="flex absolute right-14 gap-4">
        <li>
          <Link
            href="#"
            className="text-xs"
            prefetch={false}
          >
            blog
          </Link>
        </li>
        <li>
          <Link
            href="#"
            className="text-xs"
            prefetch={false}
          >
            ajuda
          </Link>
        </li>
        <li>
          <Link
            href="#"
            className="text-xs"
            prefetch={false}
          >
            histórico de pedidos
          </Link>
        </li>
        <li>
          <Link
            href="#"
            className="text-xs"
            prefetch={false}
          >
            entre para o clube
          </Link>
        </li>
      </ul>
      <div className="h-20 flex items-end justify-between px-4 py-3 bg-background border-b md:px-6">
        <Link href="#" className="flex items-center w-1/4" prefetch={false}>
          <MountainIcon className=" w-20 pl-5" />
        </Link>
        <nav className="hidden md:flex items-center justify-center w-2/4 flex-1 gap-6 ">
          <Link
            href="#"
            className="uppercase tracking-widest text-sm font-medium"
            prefetch={false}
          >
            Calçados
          </Link>
          <Link
            href="#"
            className="uppercase tracking-widest text-sm font-medium"
            prefetch={false}
          >
            Mulher
          </Link>
          <Link
            href="#"
            className="uppercase tracking-widest text-sm font-medium"
            prefetch={false}
          >
            Homem
          </Link>
          <Link
            href="#"
            className="uppercase tracking-widest text-sm font-medium"
            prefetch={false}
          >
            Infantil
          </Link>
          <Link
            href="#"
            className="uppercase tracking-widest text-sm"
            prefetch={false}
          >
            Esportes
          </Link>
          <Link
            href="#"
            className="uppercase tracking-widest text-sm"
            prefetch={false}
          >
            Mundo Adidas
          </Link>
          <Link
            href="#"
            className="uppercase tracking-widest text-sm font-medium"
            prefetch={false}
          >
            Outlet
          </Link>
        </nav>
        <div className="flex items-end gap-2 w-1/4">
          <div className="flex relative">
            <SearchIcon className="absolute right-2.5 top-2.5 h-4 w-4 " />
            <Input
              type="search"
              placeholder="Procurar"
              className=" pr-4 py-2  bg-muted"
            />
          </div>
          <ul className="flex gap-6">
            <li>
              <Link href="#">
                <Image
                  src={"/images/iconamoon--profile.svg"}
                  width={25}
                  height={15}
                  alt=""
                ></Image>
              </Link>
            </li>
            <li>
              <Link href="#">
                <Image
                  src={"/images/ph--heart-straight-bold.svg"}
                  width={25}
                  height={0}
                  alt=""
                ></Image>
              </Link>
            </li>
            <li>
              <Link href="#">
                <Image
                  src={"/images/uil--cart.svg"}
                  width={25}
                  height={15}
                  alt=""
                ></Image>
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}

type NavbarProps = React.ComponentProps<typeof Navbar>;

function MountainIcon(props: React.ImgHTMLAttributes<HTMLImageElement>) {
  return <img {...props} src="images/adidas_logo.svg"></img>;
}

type MountainIconProps = React.ComponentProps<typeof MountainIcon>;

function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
